#! /bin/sh

case "$1" in
    start)
        echo "Loading ldd modules"
        ldd_load
        ;;
    stop)
        echo "Unloading ldd modules"
        ldd_unload 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
